output: html_document
editor_options: 
  chunk_output_type: console

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(ggthemes)
library(viridis)
library(extrafont)
nz_bird <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-11-19/nz_bird.csv")
```

```{r}
glimpse(nz_bird)

  
#create a new df
by_date_hour <- 
  nz_bird %>% 
  #extract day of the week - apparently there were exactly two times of each day (14 days total)
  mutate(day_of_week = weekdays(date)) %>% 
  group_by (day_of_week, hour) %>% 
  #the count/5 is to get the number of voters, each person voted 5 times ( should be a total of 43460/5)).
  summarise(count = n()/5) %>% 
  ungroup() %>% 
  #reordering factor levels to fit the weekday scehdule
  mutate(day_of_week = ordered(day_of_week, levels = c("Sunday","Saturday","Friday", "Thursday", "Wednesday","Tuesday",  "Monday")))

#Let's see how many voted on Monday?
by_date_hour %>% 
  arrange(desc(count))


#Plot!
g <- ggplot(by_date_hour, aes(x = hour,y= day_of_week, fill =count))+
  geom_tile(color = "white", size = 0.1)+
  #This creates an equal ration for the squares of 1:1
  coord_equal()+
  #Good color scale emphasizing the highest number
  scale_fill_viridis(name = "# Voters")+
  labs(x = NULL, y = NULL, title = "NZ Bird of the Year Voting Distribution across day and time",
       subtitle = "Sunday night's tiredness generates Monday noon's peak diversion interest?",  caption = "Data: Dragonfly Data Science | @Amit_Levinson")+
  #Wanted to display all hours of the day
  scale_x_continuous(breaks = seq(0,23,1))+
      theme_tufte()

g+
  theme(text = element_text(family = "Microsoft Tai Le"),
    axis.ticks = element_blank(),
    axis.text = element_text(size = 14),
    plot.caption = element_text(size = 8, face = "italic"),
    plot.title = element_text(size = 20),
    plot.subtitle = element_text(size = 14)
  )

  ggsave("nz_bird_vote.png", width =10, height = 6)
```

