---
title: "week19-ac"
author: "Amit Levinson"
date: "5/4/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(ggtext)
library(stringr)
library(extrafont)
library(ggpomological)

user_reviews <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/user_reviews.tsv')
```


```{r}
sentiment_user_review <- user_reviews %>% 
  unnest_tokens(word, text) %>% 
  inner_join(get_sentiments("bing")) %>% 
  count(sentiment, word, sort = T) %>%
  filter(!grepl("like", word)) %>% 
  group_by(sentiment) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(word = str_to_title(word),
         n = ifelse(sentiment == "negative", -n, n),
         word = reorder(word, n))
  
ggplot(sentiment_user_review, aes(x = n, y = word, fill = sentiment))+
  geom_col(show.legend = F)+
  scale_x_continuous(breaks = seq(-300,1200,300))+
  theme_pomological()+
  scale_fill_manual(values = c(positive = "#919c4c", negative = "#c03728"))+
  labs(title = paste0("Users top 10 <b><span style='color:#919c4c'>Positive</span></b> and <b><span style='color:#c03728'>Negative</span></b> sentiments from Animal Crossing reviews"), subtitle = "Sentiment analysis excludes the word 'like' which appears 1300+ times in different contexts", caption = "Data: Villager DB | @Amit_Levinson",x = NULL, y = NULL)+
  theme(text = element_text(size = 16, family = "Roboto Condensed", color = "#a89985"),
        plot.title = element_markdown(size = 28, hjust = 0, face = "bold"),
        plot.caption = element_text(size = 10),
        panel.border = element_blank(),
        axis.text.y = element_text(size = 18),
        axis.text.x = element_text(size = 12),
        plot.margin = margin(3,2,2,2, "mm"))

ggsave("animal_cross.png", width = 16, height = 12, dpi = 320)
```



```{r}
names(critic)[2] <- "user_name" 
joined_table <- user_reviews %>% 
  mutate(user_name = "user") %>% 
  rbind(critic %>% mutate(user_name = "critic")) %>% 
  unnest_tokens(word, text) %>% 
  count(user_name, word, sort = T) %>% 
  filter(!word %in% stop_words$word,
         !str_detect(word, "\\d"))

tf_idf_joined <- joined_table %>% 
  bind_tf_idf(word,user_name,n)

tf_idf_joined %>%
  arrange(-tf_idf) %>%
  mutate(word = fct_reorder(word, tf_idf)) %>% 
  group_by(user_name) %>% 
  slice(1:10) %>%
  ungroup() %>%
  ggplot(aes(word, tf_idf, fill = user_name))+
  geom_col(show.legend = FALSE)+
  labs(x = NULL, y = "tf-idf")+
  facet_wrap(~ user_name, scales = "free_y")+
  coord_flip()

unnest_tokens(word, text) %>%
  count(author, word, sort =T) %>% 
  anti_join(stop_words)

books_tfidf <- tidy_books %>% 
    bind_tf_idf(word, author, n)

 
```







What's going on with like?
```{r}
user_reviews %>% 
  unnest_tokens(word, text, drop = FALSE) %>% 
  filter(str_detect(word, "like")) %>%
  count(word, sort = T)
  mutate(id = 1) %>% 
  filter(!word %in% stop_words$word) %>% 
  group_by(word) %>% 
  filter(n() >= 20) %>%
  ungroup() %>% 
  pairwise_cor(word, text, sort = T) %>% 
  filter(str_detect(item1, "like")) 

user_reviews %>% 
  filter(str_detect(text, "like"), str_detect(text, "start")) %>% View()

pairwise_cor(word, id, sort = T)

  separate(word, into = c("word1", "word2"), remove = FALSE) %>% 
  filter(!word1 %in% stop_words$word,
         !word2 %in% stop_words$word) %>% 
  filter(grepl("like", word))
```


```{r}
library(widyr)
```

